CREATE DATABASE IF NOT EXISTS ALX_BOOK_STORE
  CHARACTER SET UTF8MB4
  COLLATE UTF8MB4_UNICODE_CI;

USE ALX_BOOK_STORE;

CREATE TABLE IF NOT EXISTS AUTHORS (
  AUTHOR_ID INT AUTO_INCREMENT PRIMARY KEY,
  AUTHOR_NAME VARCHAR(215) NOT NULL
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS CUSTOMERS (
  CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_NAME VARCHAR(215) NOT NULL,
  EMAIL VARCHAR(215) NOT NULL,
  ADDRESS TEXT,
  UNIQUE KEY UK_CUSTOMERS_EMAIL (EMAIL)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE TABLE IF NOT EXISTS BOOKS (
  BOOK_ID INT AUTO_INCREMENT PRIMARY KEY,
  TITLE VARCHAR(130) NOT NULL,
  AUTHOR_ID INT NOT NULL,
  PRICE DOUBLE NOT NULL,
  PUBLICATION_DATE DATE,
  CONSTRAINT FK_BOOKS_AUTHORS
    FOREIGN KEY (AUTHOR_ID) REFERENCES AUTHORS (AUTHOR_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT CHK_BOOKS_PRICE_NONNEGATIVE CHECK (PRICE >= 0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE INDEX IX_BOOKS_AUTHOR_ID ON BOOKS (AUTHOR_ID);

CREATE TABLE IF NOT EXISTS ORDERS (
  ORDER_ID INT AUTO_INCREMENT PRIMARY KEY,
  CUSTOMER_ID INT NOT NULL,
  ORDER_DATE DATE NOT NULL,
  CONSTRAINT FK_ORDERS_CUSTOMERS
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS (CUSTOMER_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE INDEX IX_ORDERS_CUSTOMER_ID ON ORDERS (CUSTOMER_ID);

CREATE TABLE IF NOT EXISTS ORDER_DETAILS (
  ORDERDETAILID INT AUTO_INCREMENT PRIMARY KEY,
  ORDER_ID INT NOT NULL,
  BOOK_ID INT NOT NULL,
  QUANTITY DOUBLE NOT NULL,
  CONSTRAINT FK_ORDER_DETAILS_ORDERS
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS (ORDER_ID)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT FK_ORDER_DETAILS_BOOKS
    FOREIGN KEY (BOOK_ID) REFERENCES BOOKS (BOOK_ID)
    ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT CHK_ORDER_DETAILS_QUANTITY_POSITIVE CHECK (QUANTITY > 0)
) ENGINE=INNODB DEFAULT CHARSET=UTF8MB4;

CREATE INDEX IX_ORDER_DETAILS_ORDER_ID ON ORDER_DETAILS (ORDER_ID);
CREATE INDEX IX_ORDER_DETAILS_BOOK_ID ON ORDER_DETAILS (BOOK_ID);

INSERT INTO AUTHORS (AUTHOR_NAME) VALUES
  ('GEORGE ORWELL'),
  ('J.K. ROWLING');

INSERT INTO BOOKS (TITLE, AUTHOR_ID, PRICE, PUBLICATION_DATE) VALUES
  ('1984', 1, 9.99, '1949-06-08'),
  ('HARRY POTTER AND THE SORCERER''S STONE', 2, 12.99, '1997-06-26');

INSERT INTO CUSTOMERS (CUSTOMER_NAME, EMAIL, ADDRESS) VALUES
  ('ALICE JOHNSON', 'ALICE@EXAMPLE.COM', '123 MAIN ST'),
  ('BOB SMITH', 'BOB@EXAMPLE.COM', '456 OAK AVE');

INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE) VALUES
  (1, '2025-10-19'),
  (2, '2025-10-19');

INSERT INTO ORDER_DETAILS (ORDER_ID, BOOK_ID, QUANTITY) VALUES
  (1, 1, 1),
  (1, 2, 2),
  (2, 2, 1);
